name = "Covid19India"
uuid = "73e5f55b-545f-445b-9acb-380c00619d25"
authors = ["Tanul Gupta", "Street-Corp"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
